### ISSUE TITLE
[Feature]: 内核参数max_map_count告警级别及报错信息调整

### ISSUE THREAD

**Issue by duzp111** [oceanbase/obdiag#106]
### Describe your use case

因为内核参数配置导致集群出现问题，通过一键巡检很难快速定位原因。大部分告警级别都是warning，很难从中筛选出关键配置项。
![3cbf9ed8e4b0c7a293bfe5a184668d83](https://github.com/oceanbase/oceanbase-diagnostic-tool/assets/160576750/6f3aa91c-fd73-4779-8112-cdb141e6f798)

### Describe the solution you'd like

某些关键的内核参数如果配置有误，设置较高的告警级别，方便快速定位，告警信息可以给出此配置项对集群的影响。

**Comment by wayyoungboy** [comment]
理论上所有的warning信息都需要进行判别，可以按需将部分高危的级别提升
