### ISSUE TITLE
[Feature]: observer日志中有内存的信息打印，obdiag支持一下从日志中分析内存使用情况

### ISSUE THREAD

**Issue by Teingi** [oceanbase/obdiag#120]
### Describe your use case

observer日志中有内存的信息打印，obdiag支持一下从日志中分析内存使用情况

### Describe the solution you'd like

observer日志中有内存的信息打印，obdiag支持一下从日志中分析内存使用情况

**Comment by oraclebird** [comment]
后续可以支持
