### ISSUE TITLE
[Feature]: 建索引执行报错问题排查

### ISSUE THREAD

**Issue by Teingi** [oceanbase/obdiag#143]
### Describe your use case

建索引执行报错问题排查

### Describe the solution you'd like

obdiag 支持建索引执行报错问题排查的信息收集

**Comment by Teingi** [comment]
移动到2.2.0迭代

**Comment by wayyoungboy** [comment]
https://oceanbase.yuque.com/org-wiki-obtech-vh7w9r/imzr6c/fl9dvezvumm1oovo
