### ISSUE TITLE
[Bug]：obdiag单机库巡检本机ip走ssh报错

### ISSUE THREAD

**Issue by cishuang** [oceanbase/obdiag#208]
### Describe the bug

obdiag单机库巡检本机ip走ssh报错

### Environment

2.0.0

### Fast reproduce steps

使用obd 搭建简易observer， 搭建obdiag配置文件如下：
$cat config.yml
obcluster:
  ob_cluster_name: obcluster
  db_host: 127.0.0.1
  db_port: '2881'
  tenant_sys:
    user: root@sys
    password: xxxxxxxxxxx
  servers:
    nodes:
    - ip: 127.0.0.1 
    global:
      ssh_username: ''
      ssh_password: ''
      ssh_port: '22'
      ssh_key_file: ''
      home_path: /home/admin/oceanbase-ce
      data_dir: /home/admin/oceanbase-ce/store
      redo_dir: /home/admin/oceanbase-ce/store
执行#obdiag check报错
check start ...
[ERROR] can't get version, Exception: Authentication failed.
[ERROR] execute_one Exception : can't get version, Exception: Authentication failed.
[ERROR] Internal error :execute_one Exception : can't get version, Exception: Authentication failed. 
Trace ID: e9377e6e-119f-11ef-8e43-00163e05320b

### Expected behavior

不走ssh

### Additional context

![L1VzZXJzL2Npc2h1YW5nL0xpYnJhcnkvQXBwbGljYXRpb24gU3VwcG9ydC9pRGluZ1RhbGsvNDQ0MDM2NzU3NF92Mi9JbWFnZUZpbGVzLzE3MTU2NTY0MzE0MDhfQkQyMzgyMUMtRUU1Ri00RDE2LThCQ0QtNEEyNDI5MzY1NUFCLnBuZw==](https://github.com/oceanbase/obdiag/assets/74485635/19264af7-7f51-4fe3-9945-699805498d19)

**Comment by wayyoungboy** [comment]
目前巡检全局使用remote的方式执行指令，这个方式确实存在缺陷：
对于本机执行同时没有启用ssh server的集群中无法建立ssh连接，导致使用obdiag check受限。

我们预计将在2.3.0或2.4.0版本中重构这个执行cmd的底层基座同时也会增加k8s的场景支持。

**Comment by Teingi** [comment]
#209
