### ISSUE TITLE
[Enhancement]: The log module needs to add an elimination mechanism 日志模块需要增加淘汰机制

### ISSUE THREAD

**Issue by wayyoungboy** [oceanbase/obdiag#210]
### Description

There is currently no elimination mechanism for log files, which has led to the accumulation of previous logs, which is unreasonable for the positioning of the. obdiag hidden folder.
We need to add a log elimination mechanism to eliminate logs based on time or size.

日志文件目前没有淘汰机制，导致往期日志一直堆积，这对 .obdiag 这个隐藏文件夹的定位是不合理的。
需要增加日志淘汰机制，根据时间或者大小进行淘汰。

**Comment by Teingi** [comment]
已经处理过了，默认保存30天的日志，https://github.com/oceanbase/obdiag/blob/master/stdio.py#L430
handler = handlers.TimedRotatingFileHandler(self.log_path, when='midnight', interval=1, backupCount=30)
