### ISSUE TITLE
[Feature]: observer参数比对工具

### ISSUE THREAD

**Issue by xuji755** [oceanbase/obdiag#217]
### Describe your use case

不同的OBSERVER允许设置不同的参数，对于分布式数据库而言，检查参数设置是否合理十分关键。检查某个租户涉及的OBSERVER上面参数配置存在差异的地方

### Describe the solution you'd like

功能1-参数全面扫描
1、列出非默认参数列表
2、标识该参数是否在所有OBSERVER上配置都相同，如果存在不同，列出SERVER的，及参数配置
3、分析是否在某个OBSERVER上的参数设置不合理
功能2-某个参数的分析（功能类似功能1）
功能3-关键参数检查（类似功能1，不过需要有内置的关键参数清单）

**Comment by wayyoungboy** [comment]
![image](https://github.com/oceanbase/obdiag/assets/35394786/e934911f-2fc3-469d-a7be-9dc62cbf0c19)

Starting from version v4.2.2, Observer supports displaying default parameters
https://www.oceanbase.com/product/oceanbase-database-community-rn/releaseNote#V4.2.2

**Comment by Teingi** [comment]
#307
