### ISSUE TITLE
[Feature]: OBSERVER LIST DUMP

### ISSUE THREAD

**Issue by xuji755** [oceanbase/obdiag#218]
### Describe your use case

DUMP出OBSERVER列表及其关键指标

### Describe the solution you'd like

DUMP出OBSERVER LIST及相关信息

### Describe alternatives you've considered

信息清单如下：
1、基本信息
   所在服务器IP/PORT
   所属ZONE
   分配的 CPU/内存/文件系统容量等基本信息
2、状态信息：
    创建时间
    启动时间
    状态
    所在服务器的CPU使用率
    所在服务器的内存使用率
   所在服务器的IO延时
   OBSERVER进程的OOM SCORE
   。。。

**Comment by Teingi** [comment]
这个需求直接放在2.2.0上做，在这个采集场景中补充点信息即可完成，https://github.com/oceanbase/obdiag/blob/master/handler/gather/tasks/observer/base.yaml
