### ISSUE TITLE
[Feature]: 支持在创建索引前评估待创建的索引大小

### ISSUE THREAD

**Issue by askdb** [oceanbase/obdiag#229]
### Describe your use case

创建索引的时候会有一定的空间放大，针对一些大表，非常有必要在创建前评估一下待创建索引的空间。

### Describe the solution you'd like

创建索引的时候会有一定的空间放大，针对一些大表，非常有必要在创建前评估一下待创建索引的空间。

**Comment by wayyoungboy** [comment]
可以加到analyze的功能集合下
