### ISSUE TITLE
[Enhancement]: ddl_disk_full 提供完善的帮助命令

### ISSUE THREAD

**Issue by askdb** [oceanbase/obdiag#230]
### Description

**obdiag --version**
OceanBase Diagnostic Tool: 2.0.0
BUILD_TIME: Apr 11 2024 11:07:02OURCE

**obdiag rca run --scene=ddl_disk_full**
[ERROR] rca_scene.init err: table_name or tenant_name is None. Please check the input parameters.
Trace ID: f3db1f70-226f-11ef-8420-00163e043166

**obdiag rca run --scene=ddl_disk_full --help**
Usage: obdiag rca run [options]

Options:
  --scene=SCENE         rca scene name. The argument is required.
  --store_dir=STORE_DIR
                        the dir to store rca result, current dir by default.
  --input_parameters=INPUT_PARAMETERS
                        input parameters of scene
  -c C                  obdiag custom config
  -h, --help            Show help and exit.
  -v, --verbose         Activate verbose output.

希望能提供完整的帮助命令，增强工具的易用性。

**Comment by Teingi** [comment]
good suggestion
