### ISSUE TITLE
[Enhancement]: ddl_disk_full 根因分析优化

### ISSUE THREAD

**Issue by askdb** [oceanbase/obdiag#231]
### Description

**优化1**
obdiag rca run --scene=ddl_disk_full --input_parameters='{"tenant_name":"x1","table_name":"x2","action_type":"add_index","index_name":"x3"}'

**这里需要支持传database_name，避免同租户不同库下同名的表。**

`MySQL [test]> create table t6(c1 int,c2 int) ;
Query OK, 0 rows affected (0.21 sec)

MySQL [test]> create index idx_c2 on t6(c2);
Query OK, 0 rows affected (0.90 sec)

MySQL [test]> create database test2;
Query OK, 1 row affected (0.09 sec)

MySQL [test]> use test2;
Database changed
MySQL [test2]> create table t6(c1 int,c2 int) ;
Query OK, 0 rows affected (0.18 sec)

MySQL [test2]> create index idx_c2 on t6(c2);
Query OK, 0 rows affected (0.88 sec)`

**优化2**
查 __all_virtual_tablet_sstable_macro_info 虚拟表的时候目前只根据table_id进行过滤，建议再加上 tenant_id和 ls_id进行过滤,否则会有性能问题，导致长时间查询不到结果。

https://github.com/oceanbase/obdiag/blob/v2.1.0/handler/rca/scene/ddl_disk_full_scene.py

**Comment by xiaodong-ji** [comment]
【领取任务】
