### ISSUE TITLE
[Enhancement]:obdiag优化

### ISSUE THREAD

**Issue by chyff** [oceanbase/obdiag#237]
### Description

通过obd 自带的obdiag进行巡检,发现两个问题
问题一:
最新的内核参数指导应删除net.ipv4.tcp_tw_reuse此参数
![image](https://github.com/oceanbase/obdiag/assets/33062193/9bb46e76-3516-4525-b920-35dc2c8d0ad7)
问题二:
对于部分系统可能存在clog盘无法感知的问题，需要通过额外增加字符“/”来加强获取逻辑
![image](https://github.com/oceanbase/obdiag/assets/33062193/f5eb9650-5132-4a67-90bf-81680881ed7e)
![image](https://github.com/oceanbase/obdiag/assets/33062193/bbc4c2e8-6273-4de9-8090-f97e14b65f82)

**Comment by Teingi** [comment]
感谢反馈，欢迎提PR参与修复 ～

**Comment by Teingi** [comment]
good job!
