### ISSUE TITLE
[Bug]: column_storage.tenant_parameters 部分配置调整后检查不生效（合理）

### ISSUE THREAD

**Issue by askdb** [oceanbase/obdiag#273]
### Describe the bug

![image](https://github.com/oceanbase/obdiag/assets/29743824/a4a3fd94-7765-4066-98dc-de084d87afab)

1、1002租户的 max_allowed_packet 变量已经调整为64M，在输出告警结果中仍然会有。
2、类似 1001 这些meta租户是不是可以不用设置。

### Environment

obdiag 2.2.0
ob4.3.1.0

### Fast reproduce steps

1、调整用户租户的 set global max_allowed_packet=67108864;
2    使用 obdiag 2.2.0 分析 column_storage.tenant_parameters

**Comment by Teingi** [comment]
1. 第一个参数问题应该是obdiag的bug;
2. obdiag 工具侧是不感知那个租户是meta租户，哪些是业务租户的。

**Comment by wayyoungboy** [comment]
2这个可以优化下，check加个判断，走个偶数判断
