### ISSUE TITLE
[Enhancement]: [SQL Monitor Report ] When there is no data in gv$sql_plan_monitor , don't display sql plan monitor

### ISSUE THREAD

**Issue by Teingi** [oceanbase/obdiag#274]
### Description

![image](https://github.com/oceanbase/obdiag/assets/35712518/00545d30-136c-43ad-9945-2e4c49c1c447)

**Comment by Teingi** [comment]
有plan_monitor时候：
![image](https://github.com/oceanbase/obdiag/assets/35712518/aee35bfc-4838-4054-92d9-cd5635ac89a7)

没有的时候需要隐藏掉这部分内容

**Comment by Zxf-xufeng** [comment]
建议如果没有sql plan monitor产生时，提示可以加/*+ monitor*/再执行，获取执行详情
