### ISSUE TITLE
[Enhancement]: obdiag SQL诊断调优支持列出集群拓扑、表分布信息

### ISSUE THREAD

**Issue by Zxf-xufeng** [oceanbase/obdiag#277]
### Description

obdiag SQL诊断调优支持列出集群拓扑、表分布信息，这个对执行计划可能也有影响

**Comment by Teingi** [comment]
obdiag gather scene run --scene=observer.perf_sql --env "{db_connect='-h127.0.0.1 -P2881 -utest@test -p****** -Dtest', trace_id='Yxx'}"
