### ISSUE TITLE
[Question]: 您好，我参加了天池比赛，想详细了解一下此项目

### ISSUE THREAD

**Issue by YSevenK** [oceanbase/obdiag#282]
### Description

您好，我想详细了解一下这三个诉求：`1. OceanBase 内核：oblogminer 优化，对obcdc 4.3.1 输出信息重新打标`；`2. obdiag: OceanBase 自动化诊断工具，使用插件化开发方式` ；`3. ODC：OceanBase 开发者中心，全场景数据库开发和数据管理协同工作`。感谢您的帮助

**Comment by Teingi** [comment]
我给你提供一些共建的资料：
1. oblogminer: https://oceanbase.yuque.com/org-wiki-obtech-vh7w9r/qhlvhn/ooh262gfg3mobq16
2. obdiag : https://oceanbase.yuque.com/org-wiki-obtech-vh7w9r/imzr6c 
3. ODC： https://github.com/oceanbase/odc

**Comment by Teingi** [comment]
另外obdiag 成立了专门的obdiag SIG(特别兴趣小组)，添加 OB社区小助手（微信号：obce666）并备注“obdiag SIG”，工作人员会联系并指引您加入SIG的相关事宜。每周我们有对外的SIG周会，周会上也会同步天池比赛OceanBase这边的进度，欢迎加入参与共建。

**Comment by YSevenK** [comment]
> 我给你提供一些共建的资料：
> 
> 1. oblogminer: https://oceanbase.yuque.com/org-wiki-obtech-vh7w9r/qhlvhn/ooh262gfg3mobq16Blogminer：https://oceanbase.yuque.com/org-wiki-obtech-vh7w9r/qhlvhn/ooh262gfg3mobq16
> 2. obdiag : https://oceanbase.yuque.com/org-wiki-obtech-vh7w9r/imzr6cobdiag：https://oceanbase.yuque.com/org-wiki-obtech-vh7w9r/imzr6c
> 3. ODC： https://github.com/oceanbase/odcODChttps://github.com/oceanbase/odc

好的，非常感谢

**Comment by YSevenK** [comment]
> 另外obdiag 成立了专门的obdiag SIG(特别兴趣小组)，添加 OB社区小助手（微信号：obce666）并备注“obdiag SIG”，工作人员会联系并指引您加入SIG的相关事宜。每周我们有对外的SIG周会，周会上也会同步天池比赛OceanBase这边的进度，欢迎加入参与共建。

好的，已经添加，谢谢

**Comment by YSevenK** [comment]
> 我给你提供一些共建的资料：
> 
> 1. oblogminer: https://oceanbase.yuque.com/org-wiki-obtech-vh7w9r/qhlvhn/ooh262gfg3mobq16
> 2. obdiag : https://oceanbase.yuque.com/org-wiki-obtech-vh7w9r/imzr6c
> 3. ODC： https://github.com/oceanbase/odc

是否可以仿照 https://github.com/oceanbase/obdiag/issues/351 来添加测试和注释，还有哪些模块没做吗

**Comment by Teingi** [comment]
> > 我给你提供一些共建的资料：
> > 
> > 1. oblogminer: https://oceanbase.yuque.com/org-wiki-obtech-vh7w9r/qhlvhn/ooh262gfg3mobq16
> > 2. obdiag : https://oceanbase.yuque.com/org-wiki-obtech-vh7w9r/imzr6c
> > 3. ODC： https://github.com/oceanbase/odc
> 
> 是否可以仿照 #351 来添加测试和注释，还有哪些模块没做吗

可以的，obdiag 单测缺少很多，你可以看看common下面的那些通用代码，那些都是可以补充单测的

**Comment by YSevenK** [comment]
> > > 我给你提供一些共建的资料：
> > > 
> > > 1. oblogminer: https://oceanbase.yuque.com/org-wiki-obtech-vh7w9r/qhlvhn/ooh262gfg3mobq16
> > > 2. obdiag : https://oceanbase.yuque.com/org-wiki-obtech-vh7w9r/imzr6c
> > > 3. ODC： https://github.com/oceanbase/odc
> > 
> > 
> > 是否可以仿照 #351 来添加测试和注释，还有哪些模块没做吗
> 
> 可以的，obdiag 单测缺少很多，你可以看看common下面的那些通用代码，那些都是可以补充单测的

提了PR尝试了一下 https://github.com/oceanbase/obdiag/pull/371

**Comment by Teingi** [comment]
> > > > 我给你提供一些共建的资料：
> > > > 
> > > > 1. oblogminer: https://oceanbase.yuque.com/org-wiki-obtech-vh7w9r/qhlvhn/ooh262gfg3mobq16
> > > > 2. obdiag : https://oceanbase.yuque.com/org-wiki-obtech-vh7w9r/imzr6c
> > > > 3. ODC： https://github.com/oceanbase/odc
> > > 
> > > 
> > > 是否可以仿照 #351 来添加测试和注释，还有哪些模块没做吗
> > 
> > 
> > 可以的，obdiag 单测缺少很多，你可以看看common下面的那些通用代码，那些都是可以补充单测的
> 
> 提了PR尝试了一下 #371

good job

**Comment by Teingi** [comment]
提交代码后需要确认是否报名成功了，步骤如下：
报名参赛步骤：报名——下载选手方案提交模版——提交结果
赛事报名官网：https://tianchi.aliyun.com/competition/entrance/532215/submission/1282​
![image](https://github.com/user-attachments/assets/641e8505-d377-4176-a7e5-ed75a21de567)
表格内容要求：​
1. 选手需提供GitHub个人设置页面截图和通义灵码辅助编码使用截图（此项在提交模板里有参考截图示意。）​
2. 相关内容需要填写：
![image](https://github.com/user-attachments/assets/2ae64f77-e8d2-44e6-87ae-e70b6a519daa)
将​参赛表格​内容填写后，提交到【提交结果】中​
![image](https://github.com/user-attachments/assets/12b38131-7a50-493b-b81f-135fd155e422)
如有疑问可加入赛事交流群：钉钉群号：75530009710​
