### ISSUE TITLE
[Feature]: 关于OBDIAG对收集的日志进行脱敏的建议

### ISSUE THREAD

**Issue by way2questions** [oceanbase/obdiag#374]
### Describe your use case

目前OB和OBPROXY的日志内不可避免的会记录一下SQL信息，这些SQL信息可能会包含敏感数据，需要脱敏

### Describe the solution you'd like

1，在obdiag收集OB日志后或收集过程中，将目前OB日志内与业务相关的SQL语句(select、delete、update、insert)中的敏感信息（包括但不限于姓名、性别、手机号、银行卡号、联系方式）进行部分或全部脱敏

2，在obdiag收集OB日志后或收集过程中，将目前OBPROXY日志内与业务相关的SQL语句(select、delete、update、insert)中的敏感信息（包括但不限于姓名、性别、手机号、银行卡号、联系方式）进行部分或全部脱敏

例子：假设OB日志内有如下SQL：
`select name from testtable where phone='12345678901' and name='jack'`
脱敏后：
`select name from testtable where phone='123*****901' and name='j**k'`

**Comment by way2questions** [comment]
在代码实现上，可能不可避免的要逐行读取日志然后写入新文件，需要考虑的几个点：
1，新生成的文件，需要考虑不对obdiag的其他模块的使用产生影响（如根因分析模块的日志分析功能）
2，新生成的文件在文件修改时间，操作系统文件排序上应该与原始文件也是不同的，故在进行原始文件的读取、新的文件的创建写入等操作时，需要保证与原始文件的顺序相对一致

**Comment by Teingi** [comment]
方式1：支持第三方脚本来脱敏；
方式2：obdiag 本身对日志脱敏；

支持用户选择
