### ISSUE TITLE
[Enhancement]: obdiag major_hold的时候同时收集或者分析一下操作系统日志里是否有异常

### ISSUE THREAD

**Issue by askdb** [oceanbase/obdiag#384]
### Description

最近处理的问题，卡合并，最终定位是操作系统磁盘异常，替换节点后恢复正常，希望 obdiag major_hold 卡合并的根因分析可以同时收集或者分析一下操作系统日志是否有异常。

/var/log/messages

dmesg -T

**Comment by wayyoungboy** [comment]
1. /var/log/messages文件权限较高，不容易获取；
2. 计划将各个节点的dmesg -T进行采集
