### ISSUE TITLE
[Feature]: 4.2.1.3版本及以下，创建多个root用户可能导致统计信息收集任务失败

### ISSUE THREAD

**Issue by zxbange** [oceanbase/obdiag#385]
### Describe your use case

在4.2.1.3版本及以下，用户租户中如果有多个root用户，即使host不同的情况下，也会出现统计信息任务调度异常，收集失败的情况，例如下面这种
![image](https://github.com/user-attachments/assets/f19ea810-310e-481e-9e4f-6ede5f661c4c)
导致用户的统计信息收集任务失败
![image](https://github.com/user-attachments/assets/c2eb16ea-f00a-4be4-9e26-612dee7cd8b7)

### Describe the solution you'd like

目前只能有一个root用户，才能保证收集正常

**Comment by wayyoungboy** [comment]
实现通过oceanbase.CDB_OB_USERS查同一TENANT_ID下是否有多个root用户
