### ISSUE TITLE
[Enhancement]:  关于巡检中的table.information_schema_tables_two_data中报错的问题详解

### ISSUE THREAD

**Issue by wayyoungboy** [oceanbase/obdiag#390]
### Description

现象：一张表在information_schema.tables 中查到的有两条记录，两条记录的原因是__all_table_stat 中同时存在两条object_type=1的记录。
原因分析: 非分区表转分区表 ddl，导致一些视图（如 information_schema.tables/all_tables）会多显示一条记录
observer修复版本： 421bp5/423/431
应急方法：手动删除 __all_table_stat/__all_column_stat 中不符合预期的行（分区表不应该存在 table_id=partition_id=该表id 的记录）
1. 登录到 sys 租户上
2. 切到用户租户：alter system change tenant 租户名
3. 删内部统计信息的行
delete from __all_table_stat where table_id=partition_id and table_id=分区表table_id;
delete from __all_column_stat where table_id=partition_id and table_id=分区表table_id;

**Comment by Teingi** [comment]
1. 补充到知识库；
2. obdiag 巡检中也可以给出该issue的链接；
