### ISSUE TITLE
[Enhancement]: observer.backup 和 backup_clean 收集场景优化

### ISSUE THREAD

**Issue by askdb** [oceanbase/obdiag#397]
### Description

1、4.x 物理备份恢复是租户级别的，目前obdiag收集了所有租户,希望能根据指定的租户进行收集。
2、针对用户的环境里租户特别多，当前收集所有租户，部分sql中使用了 limit 20，导致收集的信息里没有要看的租户信息。
3、部分sql查询后带order by 默认是升序，关注的是最近时间的记录，limit 20后导致收集后的结果没有需要的时间对应的信息，查询的sql里需要按照时间降序。

**Comment by Teingi** [comment]
obdiag 2.6.0 已支持按照租户收集，同时去除了 Limit 20的限制
