### ISSUE TITLE
[Enhancement]: ssh_client 支持 Kerberos 模式

### ISSUE THREAD

**Issue by Teingi** [oceanbase/obdiag#439]
### Description

需求来源：https://ask.oceanbase.com/t/topic/35612027

需求：因为我们的服务器使用到了kerberos认证，obdiag/OCP ssh到我们的服务器上经常因为额外的klist: No credentials cache found (filename: /tmp/krb5cc_1003)输出导致一些检查失败，OCP会因为这个导致服务器导入失败。

**Comment by wayyoungboy** [comment]
我理解用户的需求应该是对 klist: No credentials cache found (filename: /tmp/krb5cc_1003) 这种数据进行删除即可

**Comment by Teingi** [comment]
> 我理解用户的需求应该是对 klist: No credentials cache found (filename: /tmp/krb5cc_1003) 这种数据进行删除即可

是的，只有第一次的时候会有这个报错，而且不是阻塞的
