### ISSUE TITLE
[Enhancement]: hacktoberfest 2024

### ISSUE THREAD

**Issue by Teingi** [oceanbase/obdiag#457]
### Description

info: https://hacktoberfest.com/

**Comment by Teingi** [comment]
https://github.com/orgs/oceanbase/projects/17

**Comment by Aditya-132** [comment]
Can i work on this issue

**Comment by Sofiyan-coder** [comment]
Hi @Teingi  , could you please assign this issue to me? I'd love to contribute and start my open-source journey with this project!

**Comment by Teingi** [comment]
> Can i work on this issue

Yes, we welcome your contributions, whether it's fixing issues, handling requests, or even adding unit tests to the project. After our review and approval, we will merge your contribution PRs into the main repository, and you can participate in Hacktoberfest 2024.

**Comment by Teingi** [comment]
> Hi @Teingi , could you please assign this issue to me? I'd love to contribute and start my open-source journey with this project!

We welcome your contributions, whether it's fixing issues, handling requests, or even adding unit tests to the project. After our review and approval, we will merge your contribution PRs into the main repository, and you can participate in Hacktoberfest 2024.

**Comment by wizaye** [comment]
hey @Teingi would like to make a contribution for this issue, could you please assign this issue to me ?

**Comment by Teingi** [comment]
> We welcome your contributions, whether it's fixing issues, handling requests, or even adding unit tests to the project. After our review and approval, we will merge your contribution PRs into the main repository, and you can participate in Hacktoberfest 2024.

We welcome your contributions, whether it's fixing issues, handling requests, or even adding unit tests to the project. After our review and approval, we will merge your contribution PRs into the main repository, and you can participate in Hacktoberfest 2024.
