### ISSUE TITLE
[Enhancement]: obdiag check 巡检增加 glibc 版本检查项

### ISSUE THREAD

**Issue by askdb** [oceanbase/obdiag#469]
### Description

glibc 从 2.34 版本开始废弃了配置全局钩子变量，详见 glibc Release：

- https://sourceware.org/glibc/wiki/Release/2.34
- Remove malloc hooks: https://patchwork.sourceware.org/project/glibc/list/?series=2369

废弃的结果是运行期钩子直接失效，回退到原生接口。此时只要调用 malloc_usable_size，observer就会crash掉，因此建议在 obdiag 巡检项里新增 glibc 版本号的检查。

使用的命令: ldd --version 

ldd (GNU libc) **2.17**
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by Teingi** [comment]
👌

**Comment by Teingi** [comment]
需要关注一下不同操作系统的兼容性测试

**Comment by Teingi** [comment]
已完成，随obdiag 2.5.0 发布
