### ISSUE TITLE
[Feature]: build a docker image about obdiag dev env

### ISSUE THREAD

**Issue by wayyoungboy** [oceanbase/obdiag#493]
### Describe your use case

计划构建一个obdiag 开发环境的dokcer镜像，降低一开始参与obdiag共建同学的学习门槛。需要内置的环境依赖如下：

ssh server：用于远程连接开发环境；
python3.8：obdiag开发环境基础；
obdiag原有的python依赖：较少需要额外安装的包；
基于阿里云源的centos7.9：方便打包和统一环境；
git：用于同步代码。
.....
还有更多的想法大家可以讨论下。
We plan to build a dokcer image for the obdiag development environment in order to lower the learning curve for new students joining the obdiag co-construction project. The required built-in environment dependencies are as follows:

ssh server: for remote connections to the development environment;
python3.8: the foundation of obdiag development environment;
obdiag's original python dependencies: requiring minimal additional installation of packages;
CentOS 7.9 based on Aliyun source: for easy packaging and standardized environment;
.....
There are more ideas for discussion.

### Describe the solution you'd like

在obdiag项目下新建一个dev的目录，并在其内新建一个Dockerfile文件，并在其中描述所需要的镜像构件流程。

**Comment by zhijia3278** [comment]
assign to me

**Comment by wayyoungboy** [comment]
可以参考使用.devcontainer 的方案

> 分配给我

**Comment by wayyoungboy** [comment]
主要考虑到拉取仓库以及github key的配置，这个需要开发者来进行配置，不知道什么方案更加合适

**Comment by zhijia3278** [comment]
正在研究devcontainer
