### ISSUE TITLE
[Enhancement]: display展示功能优化

### ISSUE THREAD

**Issue by jingyd66** [oceanbase/obdiag#514]
### Description

多条sql执行时，通过标题的形式展示区分，清晰看懂对应的结果集都是什么意义

**Comment by Teingi** [comment]
方案建议：可以在现有的display场景yaml文件中增加一个tittle字段用于展示标题。比如：
![image](https://github.com/user-attachments/assets/51a80ef1-e495-4416-8d54-1b9a691b49a4)

代码中只需要判定一下是否存在tittle字段，存在则展示
![image](https://github.com/user-attachments/assets/546bdadc-8147-456a-a9cf-d0d3d86cfaab)


最终的效果就像：
![image](https://github.com/user-attachments/assets/e93e9203-9c80-447a-a394-71ff08ef36f3)

以上建议仅供参考
