### ISSUE TITLE
[Enhancement]: 外挂脚本管理优化

### ISSUE THREAD

**Issue by wayyoungboy** [oceanbase/obdiag#518]
### Description

python脚本的调用统一
1. python外挂脚本脚本的调用方式将进行统一的方式进行加载，包括命名，加载方式。
2. 加载后所使用的方法不受限制。
3. 原硬编码在内核的代码部分全部进行迁移至外部。
4. 规范每个功能的工作区，即为~/.obdiag/{功能名}/

**Comment by xiaodong-ji** [comment]
【领取任务】
