### ISSUE TITLE
[Feature]: 检查datafile_next参数是否为0

### ISSUE THREAD

**Issue by zxbange** [oceanbase/obdiag#573]
### Describe your use case

当设置了datafile_maxsize时，并且大于datafile_size情况下，检查datafile_next是否为0，如果这个值为0，那么数据文件还是不会增长

### Describe the solution you'd like

datafile_next为0的话在巡检报告里提示

**Comment by Teingi** [comment]
select svr_ip,svr_port,zone,name,value from gv$ob_parameters where name in ('datafile_next','datafile_maxsize') order by zone,name;
