### ISSUE TITLE
[Enhancement]: add build_rpm.sh for devcontainer

### ISSUE THREAD

**Issue by wayyoungboy** [oceanbase/obdiag#592]
### Description

Recently, GitHub changed the Node.js version in the workflow, causing the original packaging pipeline to fail. To meet the demand for temporary package creation, a local Docker-based packaging strategy has been temporarily added to the developer manual. Additionally, a new packaging script, ./build_rpm.sh, has been introduced.

This script was developed based on DEVContainer. Developers need to enter the development container and execute sh build_rpm.sh in the root directory. After packaging, the default package path will be located at /root/rpmbuild/RPMS/x86_64.

-------------
近期github变更了workflow上的node版本，导致原打包流水线失败。为了满足大家打临时包的需求，开发者手册中临时增加本地基于docker的打包策略。同时新增了打包脚本 ./build_rpm.sh
该脚本基于DEVContain开发，开发者使用的时候，需要进入到开发容器后，在根目录执行sh build_rpm.sh，打包完后默认的包路径在 /root/rpmbuild/RPMS/x86_64

**Comment by YOMO-Lee** [comment]
assign to me
