### ISSUE TITLE
[Enhancement]: 建议在 observer.perf_sql  添加 dbms_xplan.display_cursor  信息的收集

### ISSUE THREAD

**Issue by askdb** [oceanbase/obdiag#601]
### Description

参考：https://www.oceanbase.com/docs/common-oceanbase-database-cn-1000000001573694

1: proxy”保持“会话
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
2: 执行查询
执行业务sql;
3: 使用DBMS_XPLAN包配合sql_audit查看上一个计划
select dbms_xplan.display_cursor(0, 'all');

**Comment by Teingi** [comment]
![image](https://github.com/user-attachments/assets/2b6b3e45-aa9c-402b-8eb1-986692867061)
