### ISSUE TITLE
[Doc]: 文档中锁冲突分析给的命令缺少租户参数

### ISSUE THREAD

**Issue by hlfox** [oceanbase/obdiag#606]
### Description

目前最新版本V2.6.0的文档中，“根因分析场景：锁冲突 lock_conflict” 给出的命令是：obdiag rca run --scene=lock_conflict 
执行会报错：[ERROR] rca_scene.execute err: can not find tenant id by tenant name: None.
提示没有指定租户，需要补充指定租户的参数。

### Documentation links

https://www.oceanbase.com/docs/common-obdiag-cn-1000000001768199

**Comment by Teingi** [comment]
ok, thanks

**Comment by Teingi** [comment]
文档已更新
