### ISSUE TITLE
[Enhancement]: observer.cpu_high 场景收集时提前检查是否有 perf 命令

### ISSUE THREAD

**Issue by askdb** [oceanbase/obdiag#620]
### Description

使用如下命令 obdiag gather scene run --scene=observer.cpu_high 收集的时候 ，会采集 obstack、perf、clocksource 等信息，当对应的环境里没有 perf 命令时，需要在收集的过程中提示出来，避免收集空的 perf 文件。
![image](https://github.com/user-attachments/assets/cdbb371f-ea8b-4174-8672-2251732690e1)

**Comment by Teingi** [comment]
A very reasonable issue, we will support it in version 3.0.0.
