### ISSUE TITLE
[Bug]: rca disconnection 报异常

### ISSUE THREAD

**Issue by alfredsongl** [oceanbase/obdiag#627]
### Describe the bug

![11](https://github.com/user-attachments/assets/521fca20-444a-451a-a9e2-ec1de0a942ab)
![12](https://github.com/user-attachments/assets/fb31e6c0-2023-4611-a420-9adffe58de75)

提示显示不友好

### Environment

2.6.0

### Fast reproduce steps

obdiag rca run --scene=disconnection

**Comment by Teingi** [comment]
observer 节点没有Zip,提示不友好，2.6.0 上修复
